name: security
on:
  push:
    branches: [main, devops]
  pull_request:

permissions:
  contents: read
  security-events: write
  id-token: write
  attestations: write

jobs:
  base:
    uses: ./.github/workflows/_security-base.yml
    with:
      site-type: next
      scan-containers: false
      working-directory: app
      semgrep-rulesets: "tools/semgrep-custom/square-token-wrapper.yaml tools/semgrep-custom/webhook-signature.yaml p/owasp-top-ten p/javascript p/typescript p/nextjs p/react"
